  - name: Add Application user
    ansible.builtin.user:
      name: roboshop

  - name: Remove Directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: Create Directory
    ansible.builtin.file:
      path: /app
      state: directory
    
  - name: Download the application code
    ansible.builtin.unarchive:
      src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip 
      dest: /app
      remote_src: yes

 

